apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: block.csi.vultr.com
spec:
  attachRequired: true
  podInfoOnMount: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: block.csi.vultr.com

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-retain
  namespace: kube-system
provisioner: block.csi.vultr.com
reclaimPolicy: Retain
