apiVersion: v2
name: vultr-csi
version: 2.0.0
description:  A Helm chart for Vultr's Container Storage Interface.
type: application
home: https://github.com/vultr/vultr-csi
sources:
    - https://github.com/vultr/vultr-csi
maintainers:
  - name: David Dymko
icon: https://helm-charts.ewr1.vultrobjects.com/icons/vultr.svg
appVersion: "v0.3.0"